# Generated by Django 3.0.3 on 2020-03-08 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users_project',
            field=models.ManyToManyField(blank=True, related_name='users_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
